# Generated by Django 3.1.7 on 2021-04-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_nvp',
            field=models.BooleanField(default=False),
        ),
    ]
